name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build website and create HTML
        env:
          ONE_SERVER_URL: https://astral-integration.com
          CUSTOM_DOMAIN: "true"
        run: |
          yarn build
          node scripts/create-html.js
          
      - name: Check build artifacts
        run: |
          echo "Contents of dist:"
          ls -la dist/
          echo "Contents of dist/assets:"
          ls -la dist/assets/
          echo "Checking for CNAME file:"
          cat dist/CNAME
          echo "Checking for entry files:"
          find dist -name "_virtual_one-entry*.js" | sort
          
          # Copy all entry files to both dist root and dist/assets for redundancy
          mkdir -p dist/assets
          find dist -name "_virtual_one-entry*.js" -exec cp {} dist/assets/ \;
          find dist -name "_virtual_one-entry*.js" -exec cp {} dist/ \;
          
          # Create a list of all entry files
          find dist -name "_virtual_one-entry*.js" | sort > dist/entry-files.txt
          echo "Entry files list created at dist/entry-files.txt"
          cat dist/entry-files.txt

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          
      - name: Add stable entry file directly to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Clone the gh-pages branch
          git clone --depth 1 --single-branch --branch gh-pages https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git gh-pages-clone
          
          # Copy all entry files directly to gh-pages root and assets
          mkdir -p gh-pages-clone/assets
          cp dist/entry-files.txt gh-pages-clone/
          find dist -name "_virtual_one-entry*.js" -exec cp {} gh-pages-clone/ \;
          find dist -name "_virtual_one-entry*.js" -exec cp {} gh-pages-clone/assets/ \;
          
          # Add the entry file name and hash to a txt file for reference
          echo "Deployed _virtual_one-entry files ($(date))" > gh-pages-clone/entry-file-info.txt
          find dist -name "_virtual_one-entry*.js" | sort >> gh-pages-clone/entry-file-info.txt
          
          # Commit and push the changes
          cd gh-pages-clone
          git add entry-file-info.txt entry-files.txt assets/ *.js
          git commit -m "Add all entry files for redundancy" || echo "No changes to commit"
          git push || echo "No changes to push" 