name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build website
        env:
          ONE_SERVER_URL: https://astral-integration.com
        run: yarn build
        # Note: postbuild script will automatically create HTML files
        
      - name: Create CNAME files
        run: |
          echo "astral-integration.com" > dist/CNAME
          echo "astral-integration.com" > dist/client/CNAME
          echo "astral-integration.com" > CNAME
          
      - name: Run create-html script manually
        run: node scripts/create-html.js
        
      - name: Run asset sync script
        run: node scripts/sync-assets.js
        
      - name: Copy fallback files to dist
        run: |
          cp backup-index.html dist/backup-index.html
          cp assets.html dist/assets.html
          
      - name: Check build artifacts
        run: |
          echo "Contents of dist:"
          ls -la dist/
          echo "Root directory:"
          ls -la
          echo "Checking for CNAME files:"
          find . -name "CNAME" -type f

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: false  # Don't remove existing files that aren't in the dist folder 