name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build website
        env:
          ONE_SERVER_URL: https://astral-integration.com
        run: yarn build
        # Note: postbuild script will automatically create HTML files
        
      - name: Create CNAME files
        run: |
          echo "astral-integration.com" > dist/CNAME
          echo "astral-integration.com" > dist/client/CNAME
          echo "astral-integration.com" > CNAME
          
      - name: Run create-html script manually
        run: node scripts/create-html.js
        
      - name: Create stable framework files
        run: node scripts/create-stable-files.js
        
      - name: Verify stable entry script existence
        run: |
          echo "Checking for stable entry script:"
          ls -la dist/ | grep virtual
          ls -la dist/assets/ | grep virtual
          
      - name: Run asset sync script
        run: node scripts/sync-assets.js
        
      - name: Copy fallback files to dist
        run: |
          cp backup-index.html dist/backup-index.html
          cp assets.html dist/assets.html
          
      - name: Check build artifacts
        run: |
          echo "Contents of dist:"
          ls -la dist/
          echo "Virtual entry files:"
          find dist -name "*virtual*entry*.js"
          echo "Checking for CNAME files:"
          find . -name "CNAME" -type f

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: false  # Don't remove existing files that aren't in the dist folder
          
      - name: Add stable entry file directly to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Clone the gh-pages branch
          git clone --depth 1 --single-branch --branch gh-pages https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git gh-pages-clone
          
          # Create assets directory if it doesn't exist
          mkdir -p gh-pages-clone/assets
          
          # Copy the stable entry file to the gh-pages branch
          cp dist/assets/_virtual_one-entry-stable.js gh-pages-clone/assets/
          cp dist/_virtual_one-entry-stable.js gh-pages-clone/
          
          # Commit and push the changes
          cd gh-pages-clone
          git add assets/_virtual_one-entry-stable.js _virtual_one-entry-stable.js
          git commit -m "Add stable entry files" || echo "No changes to commit"
          git push || echo "No changes to push" 